export const MOCK_STUDENT = {
  name: 'Nethmi Perera',
  id: 'IT23583764',
  programme: 'BSc (Hons) IT - Year 3',
  year: 3,
  semester: 2,
  department: 'Computing & IT',
  email: 'IT23583764@my.sliit.lk',
  phone: '+94 71 234 5678',
};

export const MOCK_MODULES = [
  {
    _id: 'mod_it3060',
    code: 'IT3060',
    name: 'Human Computer Interaction',
    credits: 3,
    color: '#0284C7',
    bgColor: '#E0F2FE',
  },
  {
    _id: 'mod_it3070',
    code: 'IT3070',
    name: 'Software Engineering',
    credits: 3,
    color: '#16A34A',
    bgColor: '#DCFCE7',
  },
  {
    _id: 'mod_it3080',
    code: 'IT3080',
    name: 'Cloud Computing & Architecture',
    credits: 3,
    color: '#D97706',
    bgColor: '#FEF9C3',
  },
  {
    _id: 'mod_it3090',
    code: 'IT3090',
    name: 'Distributed Systems',
    credits: 3,
    color: '#7C3AED',
    bgColor: '#EDE9FE',
  },
  {
    _id: 'mod_it3100',
    code: 'IT3100',
    name: 'Database Administration',
    credits: 3,
    color: '#DC2626',
    bgColor: '#FEE2E2',
  },
];

export const MOCK_GROUPS = [
  // IT3060 HCI
  {
    _id: 'g_it3060_g1',
    moduleCode: 'IT3060',
    groupId: 'G1',
    groupName: 'Group 1',
    day: 'Mon',
    dayOfWeek: 'Monday',
    start: '10:00',
    end: '12:00',
    timeDisplay: 'Mon 10:00–12:00',
    venue: 'Lab 4',
    seatsLeft: 14,
    totalSeats: 30,
  },
  // IT3070 SE
  {
    _id: 'g_it3070_g2',
    moduleCode: 'IT3070',
    groupId: 'G2',
    groupName: 'Group 2',
    day: 'Mon',
    dayOfWeek: 'Monday',
    start: '10:00',
    end: '12:00',
    timeDisplay: 'Mon 10:00–12:00',
    venue: 'LH 2',
    seatsLeft: 3,
    totalSeats: 30,
  },
  {
    _id: 'g_it3070_g4',
    moduleCode: 'IT3070',
    groupId: 'G4',
    groupName: 'Group 4',
    day: 'Tue',
    dayOfWeek: 'Tuesday',
    start: '14:00',
    end: '16:00',
    timeDisplay: 'Tue 2:00–4:00pm',
    venue: 'Auditorium 3',
    seatsLeft: 12,
    totalSeats: 30,
  },
  {
    _id: 'g_it3070_g6',
    moduleCode: 'IT3070',
    groupId: 'G6',
    groupName: 'Group 6',
    day: 'Wed',
    dayOfWeek: 'Wednesday',
    start: '09:00',
    end: '11:00',
    timeDisplay: 'Wed 9:00–11:00am',
    venue: 'Lab 2',
    seatsLeft: 4,
    totalSeats: 30,
  },
  // IT3080 Cloud Computing
  {
    _id: 'g_it3080_g1',
    moduleCode: 'IT3080',
    groupId: 'G1',
    groupName: 'Group 1',
    day: 'Thu',
    dayOfWeek: 'Thursday',
    start: '11:00',
    end: '13:00',
    timeDisplay: 'Thu 11:00–13:00',
    venue: 'Lab 1',
    seatsLeft: 20,
    totalSeats: 30,
  },
  // IT3090 Distributed Systems
  {
    _id: 'g_it3090_g1',
    moduleCode: 'IT3090',
    groupId: 'G1',
    groupName: 'Group 1',
    day: 'Fri',
    dayOfWeek: 'Friday',
    start: '09:00',
    end: '11:00',
    timeDisplay: 'Fri 9:00–11:00am',
    venue: 'Lab 5',
    seatsLeft: 15,
    totalSeats: 30,
  },
  // IT3100 Database Administration
  {
    _id: 'g_it3100_g1',
    moduleCode: 'IT3100',
    groupId: 'G1',
    groupName: 'Group 1',
    day: 'Fri',
    dayOfWeek: 'Friday',
    start: '13:00',
    end: '15:00',
    timeDisplay: 'Fri 13:00–15:00',
    venue: 'LH 1',
    seatsLeft: 18,
    totalSeats: 30,
  },
];

export const INITIAL_SELECTED_MODULES = [
  { moduleCode: 'IT3060', groupId: 'G1' },
  { moduleCode: 'IT3070', groupId: 'G2' },
  { moduleCode: 'IT3080', groupId: 'G1' },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_1',
    type: 'deadline',
    title: 'Registration closes in 2 days',
    text: 'Course registration for Semester 2 closes in 2 days at 11:59pm.',
    time: '2 hours ago',
    timeAgo: '2 hours ago',
    read: false,
    targetRoute: 'Register',
  },
  {
    id: 'notif_2',
    type: 'change',
    title: 'IT3080 room changed to LH2',
    text: 'IT3080 Thursday lecture venue moved to LH2.',
    time: 'Yesterday',
    timeAgo: 'Yesterday',
    read: false,
    targetRoute: 'Timetable',
  },
  {
    id: 'notif_3',
    type: 'confirmed',
    title: 'Schedule saved in draft',
    text: 'Your current course registration selections have been saved.',
    time: '3 days ago',
    timeAgo: '3 days ago',
    read: true,
    targetRoute: 'Register',
  },
];

export const INITIAL_CASES = [
  {
    id: 'case_1',
    studentName: 'Nethmi Perera',
    studentId: 'IT23583764',
    clashSummary: 'IT3060-G1 vs IT3070-G2',
    message: 'Both modules are required for my degree. Could you approve Group 4 instead?',
    status: 'conflict', // "conflict" | "awaiting" | "resolved"
    suggestedGroup: 'G4',
    suggestedModule: 'IT3070',
    suggestedDetails: 'Suggested: IT3070-G4 · 12 seats available · no new clash',
    time: '10 mins ago',
  },
  {
    id: 'case_2',
    studentName: 'Kavindu R.',
    studentId: 'IT23000001',
    clashSummary: 'IT3080 / IT3090 – awaiting seat',
    message: 'Student requires special enrollment for full prerequisite completion.',
    status: 'awaiting',
    suggestedGroup: 'G2',
    suggestedModule: 'IT3090',
    suggestedDetails: 'Suggested: Expand IT3090-G2 by 2 seats',
    time: '2 hours ago',
  },
  {
    id: 'case_3',
    studentName: 'Dinuka S.',
    studentId: 'IT23000002',
    clashSummary: 'IT3050 / IT3060 – resolved',
    message: 'Resolved by assigning Group 3 for Wednesday afternoon schedule.',
    status: 'resolved',
    suggestedGroup: 'G3',
    suggestedModule: 'IT3060',
    suggestedDetails: 'Status: Approved & Updated',
    time: '1 day ago',
  },
];

export const SYSTEM_LOGS = [
  { time: '14:25:01', event: 'Gateway sync: 200 OK (1.2s)', status: 'Success' },
  { time: '14:24:45', event: 'Seat lock auto-released (IT3070-G4)', status: 'Info' },
  { time: '14:23:12', event: 'Seat feed timeout -- 3 retries', status: 'Warning' },
  { time: '14:22:04', event: 'Concurrent active users: 312', status: 'Success' },
  { time: '14:20:00', event: 'Database Atlas connection latency: 18ms', status: 'Success' },
  { time: '14:15:30', event: 'Nightly backup completed', status: 'Success' },
];
